### ISSUE TITLE
提交文章时hexo崩溃退出

### ISSUE THREAD

**Issue by codehz** [nihgwu/hexo-hey#14]
终端上是这样显示的

```
INFO  Hexo is running at http://0.0.0.0:4000/. Press Ctrl+C to stop.
***\node_modules\hexo-hey\api.js:125
            id: post._id,
                    ^

TypeError: Cannot read property '_id' of undefined
    at ***\node_modules\hexo-hey\api.js:125:21
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
```

**Comment by codehz** [comment]
原因应该是windows和Unix下文件分隔符不同造成的
